name:                intensional-algebraic-structures
version:             0.1.0.0
github:              "zepalmer/intensional-algebraic-structures"
license:             BSD3
author:              "Zachary Palmer"
maintainer:          "zep_github@bahj.com"
copyright:           "2021-2024 Zachary Palmer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Algebraic structures defined in terms of intensional functions.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zepalmer/intensional-algebraic-structures#readme>

dependencies:
- base >= 4.15 && < 5

library:
  source-dirs: src

tests:
  intensional-algebraic-structures-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intensional-algebraic-structures
