# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/0.yaml

# Using intensional functions GHC
compiler: ghc-git-12cb0cf2e6eb91ec7a97f1cd05f6682b34cb9d97-quick
compiler-repository: https://github.com/zepalmer/intensional-functions-ghc.git

# User packages to be built.
packages: ["."]

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps: []
