# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# NOTE: this should eventually be a GHC 9.2.1 resolver, but as of this writing
#       (2022-03-29), there are no LTS resolvers using 9.2.1.  Although we don't
#       use the stock compiler, it'd help to ensure that the packages are
#       compatible with our GHC.
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/0.yaml

# Using intensional functions GHC
# NOTE: This should eventually point to a publicly visible repository.
compiler: ghc-git-cac571902c6c34d6e7aca7f9d52dd63d15e4789d-quick
compiler-repository: git.bahj.com:intensional-functions-ghc

# User packages to be built.
packages: ["."]

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps: []
